version: '3.8'

services:
  waveify-api:
    build: .
    container_name: waveify-backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - waveify-network

  # Optional: Add nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: waveify-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - waveify-api
    networks:
      - waveify-network
    profiles:
      - production

networks:
  waveify-network:
    driver: bridge

volumes:
  waveify-data: